# Build settings
markdown: kramdown
highlighter: pygments

# Site settings
title: $$\sum_{i=1}^n ideology_i=\infty$$
description: > # this means to ignore newlines until "email:"
   一个老男孩的自留地

head_title: wnono.com
email: wesley.chow@wnono.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "http://s.cn.bing.net/az/hprichbg/rb/HeartNebula_ZH-CN7750020667_1920x1080.jpg"

name: 'Wesley Chow'
name_cn: '周凌'
author: 'Wesley Chow'
author_cn: '周凌'
author_image: "/assets/images/author_me.jpg"

paginate:	5

url: "http://wnono.com" # the base hostname & protocol for your site
baseurl: ""

# Comments System Setting
commentsystem: duoshuo
disqus: wnono

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/wesley_zhou
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/wezchow
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: linkedin-alt
    url: https://www.linkedin.com/in/wezchow
    desc: Get connect on Linkedin

#  - icon: googleplus-alt
#   url:  https://google.com/+IanCamporezBrunelli
#    desc: Add me on google+

  - icon: feed
    url:  /feed.xml
    desc: Subscribe to my feed

menu:
  - title:  Home [主页]
    url:  /

  - title: Blog [博客]
    url: /blog

  - title: Work [作品]
    url: /work

  - title:  Me [我]
    url:  /about

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-59478649-1

gems:
  - jekyll-sitemap